//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Scripts/Services/InputService/InputActionSheme.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActionSheme: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActionSheme()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActionSheme"",
    ""maps"": [
        {
            ""name"": ""GameplayInput"",
            ""id"": ""a39ab53e-5ab3-4236-a61b-171e40436198"",
            ""actions"": [
                {
                    ""name"": ""AimingButtonPressed"",
                    ""type"": ""Button"",
                    ""id"": ""6410dbb2-4d88-4eaa-ba34-60e3c91ff749"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UndoAimingButtonPressed"",
                    ""type"": ""Button"",
                    ""id"": ""f8bf08d4-e5e1-406f-b339-65af3b60c192"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d780404f-91fb-43d4-895f-519e8258e5e8"",
                    ""path"": ""<Keyboard>/#(1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimingButtonPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a0aa1cd-d7af-4d7b-ad1a-7d66b8090775"",
                    ""path"": ""<Keyboard>/#(2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UndoAimingButtonPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""HandleInput"",
            ""id"": ""36f04957-9222-4303-a6fb-eb1f9eac325c"",
            ""actions"": [
                {
                    ""name"": ""HandleMove"",
                    ""type"": ""Value"",
                    ""id"": ""fa1b4f5f-8588-47a4-b821-a5e65648018e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""b0cca896-bb98-4730-a119-c72ea130715a"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandleMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""ea19c317-8e5e-494d-a0d4-fa85992db1be"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandleMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Binding"",
                    ""id"": ""22515924-617f-4e3d-adca-231255c2cc39"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandleMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""86c6e22b-dc8e-4179-8aa6-4b944e7f3219"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandleMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""252c44bc-d1ce-481b-87a3-826362884170"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandleMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""6c990362-f982-41ba-9530-0e5cb558d402"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandleMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GameplayInput
        m_GameplayInput = asset.FindActionMap("GameplayInput", throwIfNotFound: true);
        m_GameplayInput_AimingButtonPressed = m_GameplayInput.FindAction("AimingButtonPressed", throwIfNotFound: true);
        m_GameplayInput_UndoAimingButtonPressed = m_GameplayInput.FindAction("UndoAimingButtonPressed", throwIfNotFound: true);
        // HandleInput
        m_HandleInput = asset.FindActionMap("HandleInput", throwIfNotFound: true);
        m_HandleInput_HandleMove = m_HandleInput.FindAction("HandleMove", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GameplayInput
    private readonly InputActionMap m_GameplayInput;
    private List<IGameplayInputActions> m_GameplayInputActionsCallbackInterfaces = new List<IGameplayInputActions>();
    private readonly InputAction m_GameplayInput_AimingButtonPressed;
    private readonly InputAction m_GameplayInput_UndoAimingButtonPressed;
    public struct GameplayInputActions
    {
        private @InputActionSheme m_Wrapper;
        public GameplayInputActions(@InputActionSheme wrapper) { m_Wrapper = wrapper; }
        public InputAction @AimingButtonPressed => m_Wrapper.m_GameplayInput_AimingButtonPressed;
        public InputAction @UndoAimingButtonPressed => m_Wrapper.m_GameplayInput_UndoAimingButtonPressed;
        public InputActionMap Get() { return m_Wrapper.m_GameplayInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayInputActions set) { return set.Get(); }
        public void AddCallbacks(IGameplayInputActions instance)
        {
            if (instance == null || m_Wrapper.m_GameplayInputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameplayInputActionsCallbackInterfaces.Add(instance);
            @AimingButtonPressed.started += instance.OnAimingButtonPressed;
            @AimingButtonPressed.performed += instance.OnAimingButtonPressed;
            @AimingButtonPressed.canceled += instance.OnAimingButtonPressed;
            @UndoAimingButtonPressed.started += instance.OnUndoAimingButtonPressed;
            @UndoAimingButtonPressed.performed += instance.OnUndoAimingButtonPressed;
            @UndoAimingButtonPressed.canceled += instance.OnUndoAimingButtonPressed;
        }

        private void UnregisterCallbacks(IGameplayInputActions instance)
        {
            @AimingButtonPressed.started -= instance.OnAimingButtonPressed;
            @AimingButtonPressed.performed -= instance.OnAimingButtonPressed;
            @AimingButtonPressed.canceled -= instance.OnAimingButtonPressed;
            @UndoAimingButtonPressed.started -= instance.OnUndoAimingButtonPressed;
            @UndoAimingButtonPressed.performed -= instance.OnUndoAimingButtonPressed;
            @UndoAimingButtonPressed.canceled -= instance.OnUndoAimingButtonPressed;
        }

        public void RemoveCallbacks(IGameplayInputActions instance)
        {
            if (m_Wrapper.m_GameplayInputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplayInputActions instance)
        {
            foreach (var item in m_Wrapper.m_GameplayInputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameplayInputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameplayInputActions @GameplayInput => new GameplayInputActions(this);

    // HandleInput
    private readonly InputActionMap m_HandleInput;
    private List<IHandleInputActions> m_HandleInputActionsCallbackInterfaces = new List<IHandleInputActions>();
    private readonly InputAction m_HandleInput_HandleMove;
    public struct HandleInputActions
    {
        private @InputActionSheme m_Wrapper;
        public HandleInputActions(@InputActionSheme wrapper) { m_Wrapper = wrapper; }
        public InputAction @HandleMove => m_Wrapper.m_HandleInput_HandleMove;
        public InputActionMap Get() { return m_Wrapper.m_HandleInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HandleInputActions set) { return set.Get(); }
        public void AddCallbacks(IHandleInputActions instance)
        {
            if (instance == null || m_Wrapper.m_HandleInputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_HandleInputActionsCallbackInterfaces.Add(instance);
            @HandleMove.started += instance.OnHandleMove;
            @HandleMove.performed += instance.OnHandleMove;
            @HandleMove.canceled += instance.OnHandleMove;
        }

        private void UnregisterCallbacks(IHandleInputActions instance)
        {
            @HandleMove.started -= instance.OnHandleMove;
            @HandleMove.performed -= instance.OnHandleMove;
            @HandleMove.canceled -= instance.OnHandleMove;
        }

        public void RemoveCallbacks(IHandleInputActions instance)
        {
            if (m_Wrapper.m_HandleInputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IHandleInputActions instance)
        {
            foreach (var item in m_Wrapper.m_HandleInputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_HandleInputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public HandleInputActions @HandleInput => new HandleInputActions(this);
    public interface IGameplayInputActions
    {
        void OnAimingButtonPressed(InputAction.CallbackContext context);
        void OnUndoAimingButtonPressed(InputAction.CallbackContext context);
    }
    public interface IHandleInputActions
    {
        void OnHandleMove(InputAction.CallbackContext context);
    }
}
